const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const script = fs.readFileSync(require.resolve('../static/app.js'), 'utf8');
const functions = script.slice(script.indexOf('function internetDetails('), script.indexOf('function renderNotebook('));
const context = {esc: value => String(value).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;')};
vm.createContext(context); vm.runInContext(functions, context);
const request = {summary:'Look up CVE-2024-3094', destination:'api.osv.dev', sending:'CVE-2024-3094', fetching:'Published advisory', reason:'<img src=x onerror=alert(1)>', sharing:'Reference data sent to Local model'};
const card = context.internetQuestion(request, ['Allow', 'Deny']);
assert.match(card, /data-answer="Allow"/); assert.match(card, /data-answer="Deny"/);
assert.match(card, /<summary>Request details<\/summary>/);
assert.doesNotMatch(card, /<details[^>]*\bopen\b/);
assert.match(card, /&lt;img/); assert.doesNotMatch(card, /<img/);
assert.match(card, /Destination/); assert.match(card, /Sending/); assert.match(card, /Fetching/);
assert.match(card, /Reason/); assert.match(card, /Model sharing/);
assert.equal(card.split('Look up CVE-2024-3094').length - 1, 1);
const page = fs.readFileSync(require.resolve('../static/index.html'), 'utf8');
assert.doesNotMatch(page, /source-review|Review together/);
console.log('PASS: internet consent choices, collapsed escaped details, removed Review together');
