# -*- coding: utf-8 -*-
from double_agent_prelude import *

class AgentAPIChunk1Chunk2(object):
    def _build_docs(self):
        """Return a self-describing API spec so any AI Agent session can onboard without prior context."""
        docs = {
            "name": "Double Agent - AI Agent API",
            "version": getattr(self.extender, "VERSION", "3.0"),
            "description": (
                "This API lets an external agentic AI (AI Agent) read security findings from a "
                "Burp Suite extension, claim work items, run manual security tests, queue autonomous "
                "automated testing work, and create new findings discovered during testing. "
                "Findings are the source of truth for the UI and generated markdown report; agents must "
                "POST confirmed new vulnerabilities to /api/findings instead of only reporting them in chat. "
                "Work items may include 'browser_verify': true, meaning the user wants the agent to "
                "verify the finding in a real browser using BrowserOS MCP tools (with traffic routed "
                "through Burp proxy at 127.0.0.1:8080). If BrowserOS MCP tools are missing, read the "
                "browseros_mcp_setup field in this document, kill old BrowserOS instances, relaunch "
                "BrowserOS in debugging/proxy mode, and register the MCP before asking the user how to proceed. "
                "The agent must ask the user in chat before "
                "any state-changing browser action. BURP MCP / PORTSWIGGER MCP is required for full operation "
                "and is on port 9876 at http://127.0.0.1:9876/ with SSE at the root path /. Use available "
                "Burp MCP tools for Burp-native actions such as sending useful requests to Repeater, adding "
                "Proxy history notes/comments, preserving Burp history context, and other Burp workflow tasks "
                "when tool support exists. For HTTP/2-only, HTTP/2-sensitive, or pseudo-header-sensitive tests, "
                "use POST /api/agent/request/http2 or the PortSwigger MCP send_http2_request tool "
                "instead of downgrading to HTTP/1.1 curl."
            ),
            "auth": {
                "type": "none",
                "reason": "The API is bound to 127.0.0.1 and is not exposed to the LAN."
            },
            "browseros_mcp_setup": {
                "when_to_use": "Use this whenever browser_verify=true, next_action.recommended_transport is browseros, or a campaign requires real browser state and BrowserOS MCP tools are not registered in the current agent session.",
                "expected_mcp_endpoint": "http://127.0.0.1:9000/mcp",
                "expected_cdp_endpoint": "http://127.0.0.1:9100/json/version",
                "claude_mcp_name": "browseros",
                "claude_register_command": "claude mcp add --transport http browseros http://127.0.0.1:9000/mcp --scope user",
                "current_session_note": "MCP registration is normally loaded by Claude Code only at process/session startup. If claude mcp add succeeds but BrowserOS tools still do not appear in the current session, first try a fresh Claude Code session. If a fresh session still lacks callable BrowserOS tools but http://127.0.0.1:9000/mcp is healthy and tools/list returns BrowserOS tools, use direct local MCP JSON-RPC control calls as the fallback. Do not ask a generic tooling question.",
                "macos_steps": [
                    "Kill existing BrowserOS instances first: pkill -f BrowserOS 2>/dev/null || true; pkill -f browseros 2>/dev/null || true; sleep 1",
                    "Launch visible BrowserOS through Burp Proxy in debugging mode: open -na 'BrowserOS' --args --proxy-server=127.0.0.1:8080 '--proxy-bypass-list=<-loopback>' --remote-debugging-port=9100 --user-data-dir=/tmp/browseros-profile --ignore-certificate-errors",
                    "Probe local BrowserOS endpoints: curl --noproxy '*' -s -m 3 http://127.0.0.1:9100/json/version; curl --noproxy '*' -s -m 3 -o /dev/null -w 'MCP_9000:%{http_code}\\n' http://127.0.0.1:9000/mcp",
                    "Register the MCP if missing: claude mcp list 2>/dev/null | grep -i browseros || claude mcp add --transport http browseros http://127.0.0.1:9000/mcp --scope user"
                ],
                "kali_linux_steps": [
                    "Prefer /usr/lib/browseros/browseros when it exists.",
                    "Cleanup first under set +e: pkill -9 -f '/usr/lib/browseros/browseros' 2>/dev/null || true; pkill -9 -f browseros_server 2>/dev/null || true; rm -f /tmp/browseros-profile/Singleton* /tmp/browseros-profile/browseros/server.lock 2>/dev/null || true",
                    "Launch with the Bash tool's background mode/run_in_background support, not nohup/setsid/& alone: exec /usr/lib/browseros/browseros --no-sandbox --proxy-server=http://127.0.0.1:8080 '--proxy-bypass-list=<-loopback>' --remote-debugging-port=9100 --user-data-dir=/tmp/browseros-profile --disable-gpu --ignore-certificate-errors",
                    "Probe after 8-12s: curl --noproxy '*' -s -m 3 http://127.0.0.1:9100/json/version >/dev/null && echo CDP_9100_OK || echo CDP_9100_FAIL; curl --noproxy '*' -s -m 3 -o /dev/null -w 'MCP_9000:%{http_code}\\n' http://127.0.0.1:9000/mcp; curl --noproxy '*' -s -m 3 -o /dev/null -w 'SERVER_9200:%{http_code}\\n' http://127.0.0.1:9200/",
                    "Register the MCP if missing: claude mcp list 2>/dev/null | grep -i browseros || claude mcp add --transport http browseros http://127.0.0.1:9000/mcp --scope user"
                ],
                "direct_jsonrpc_fallback": {
                    "when_to_use": "Use only when BrowserOS MCP is healthy but Claude Code still does not expose callable BrowserOS tools after registration/fresh session.",
                    "proxy_rule": "curl calls to http://127.0.0.1:9000/mcp are local MCP control calls, not target application traffic, so use curl --noproxy '*' and do not add -x. Browser navigation still goes through Burp because BrowserOS was launched with --proxy-server=127.0.0.1:8080.",
                    "initialize": "curl --noproxy '*' -s -m 30 -X POST http://127.0.0.1:9000/mcp -H 'Content-Type: application/json' -d '{\"jsonrpc\":\"2.0\",\"id\":1,\"method\":\"initialize\",\"params\":{\"protocolVersion\":\"2025-06-18\",\"capabilities\":{},\"clientInfo\":{\"name\":\"double-agent\",\"version\":\"1.0\"}}}'",
                    "list_tools": "curl --noproxy '*' -s -m 30 -X POST http://127.0.0.1:9000/mcp -H 'Content-Type: application/json' -d '{\"jsonrpc\":\"2.0\",\"id\":2,\"method\":\"tools/list\",\"params\":{}}'",
                    "call_tool_template": "curl --noproxy '*' -s -m 30 -X POST http://127.0.0.1:9000/mcp -H 'Content-Type: application/json' -d '{\"jsonrpc\":\"2.0\",\"id\":3,\"method\":\"tools/call\",\"params\":{\"name\":\"<tool_name_from_tools_list>\",\"arguments\":{...}}}'",
                    "known_browseros_tools": ["tabs", "tab_groups", "navigate", "snapshot", "act"],
                    "guidance": "Call tools/list first and use the returned input schemas. Prefer callable MCP tools when available; use direct JSON-RPC only as a local-control fallback."
                },
                "do_not_do": [
                    "Do not run target-application curl for browser_verify=true work. Local curl calls to http://127.0.0.1:9000/mcp are allowed only as MCP control-plane fallback.",
                    "Do not stop at 'BrowserOS MCP tools are missing' until you have checked /api/docs and attempted the setup path that matches the platform.",
                    "Do not imply that '/try now' or another message in the same Claude Code session can load newly registered MCP tools. Try a fresh Claude Code process/session, then use direct_jsonrpc_fallback if the fresh session still lacks callable tools but the MCP endpoint is healthy.",
                    "Do not use mdfind or broad filesystem search to locate BrowserOS; check /usr/lib/browseros/browseros and /Applications/BrowserOS.app first."
                ]
            },
            "typical_flow": [
                "1. GET /api/health to confirm reachable",
                "2. GET /api/docs to load current endpoint schemas and rules",
                "3. GET /api/agent/burp/skill and follow combined_markdown as the Agent B Burp operating skill; no client-side skill installation is required.",
                "4. GET /api/agent/burp/capabilities and /api/agent/burp/workspace, then GET /api/agent/scope and /api/agent/preflight?host=<target-host>&url=<exact-url> to inventory the real Burp toolset, workspace state, authoritative scope, proxy readiness, queue state, and available auth material before active testing.",
                "5. GET /api/findings and triage the existing findings before testing. Triage means classify and prioritize existing findings from their actual data (URL, title, detail_preview, evidence_preview, CWE/OWASP, request/response availability, and relationships to other findings). Triage is NOT exploitation and NOT title-only sorting.",
                "6. GET /api/agent/knowledge, /api/agent/fixtures, and /api/agent/confirmations before IDOR, tenant, MFA, OTP, automated testing, or other flow-state testing. If required test context is missing, report blocked-by-missing-fixture instead of guessing.",
                "7. GET /api/agent/queue to list work items, pick one with status=pending, and follow next_action.",
                "8. POST /api/agent/queue/<id>/claim",
                "9. GET /api/agent/queue/<id> for full request/response data and next_action metadata.",
                "10. Check next_action.recommended_transport and browser_verify: autonomous_hunt means Automated Testing has no replayable curl and must use scoped hand-built Burp-proxied requests; browseros means skip curl and use ONLY BrowserOS MCP; browser_verify=true means read browseros_mcp_setup if tools are missing; curl_proxy means call GET /api/agent/queue/<id>/curl?refresh_auth=true and run the generated command exactly.",
                "11. Run manual tests only on the prioritized set. Prefer POST /api/agent/burp/action using a semantic action and Burp-visible note; use its advertised Double Agent fallback when the native capability is unavailable. Avoid duplicate or obvious false-positive work.",
                "12. POST /api/agent/queue/<id>/result with tested outcome, severity, agent_status, agent_priority, evidence, exact request, status code, response snippet, auth source, Burp history reference if available, and reproduction notes. This updates linked finding risk/status and clears the completed queue item while preserving coverage.",
                "13. For confirmed new vulnerabilities discovered during testing, POST /api/findings so they appear in the UI and generated markdown report.",
                "14. Report tested results directly to the user after /result succeeds and any new findings have been written back."
            ],
            "endpoints": [
                {"method": "GET", "path": "/api/health", "auth": False,
                 "returns": "{status, version, queue_size, queue_pending, docs}"},
                {"method": "GET", "path": "/api/agent/prompt", "auth": False,
                 "description": "Return the current Agent B activation prompt used by Copy Agent B's Prompt so a dedicated harness can connect without clipboard transfer.",
                 "returns": "{status, agent, prompt, source, generated_at}"},
                {"method": "GET", "path": "/api/docs?compact=true", "auth": False,
                 "description": "Use compact=true for an endpoint index; omit it for complete schemas and operating rules.",
                 "returns": "compact endpoint index or this complete document"},
                {"method": "GET", "path": "/api/report?summary=true", "auth": True,
                 "description": "Use summary=true for counts and immutable finding IDs; omit it for the live markdown report.",
                 "returns": "{summary,full_report} or {summary,markdown,length,generated_at}"},
                {"method": "GET", "path": "/api/coverage?host=<host>&in_scope_only=true&limit=500&summary=true", "auth": True,
                 "description": "Cross-references Burp's site map with current findings and completed queue results to show which endpoints have been covered vs untested. Endpoints are deduped by (METHOD, host, path) with query strings collapsed. Static assets/chunks are grouped out of the default denominator unless include_static=true. Use this at start-of-session to prioritise WHERE to test next - focus on 'untested' entries that have a response.",
                 "returns": "{totals:{endpoints,covered,untested,coverage_percent,by_surface_class,by_protocol},static_asset_groups,untested,tested}; summary=true includes bounded actionable endpoint previews"},
                {"method": "GET", "path": "/api/coverage/parameters?host=<host>&in_scope_only=true&limit=500&summary=true", "auth": True,
                 "description": "Parameter-aware coverage. Cross-references Burp's site map, findings, and completed queue results by (METHOD, host, path, parameter name, parameter type) so Agent B can see untested query/body/cookie/header insertion points instead of treating a whole endpoint as covered after one test.",
                 "returns": "{totals:{parameters,covered,untested,coverage_percent,meaningful_inputs,meaningful_tested,meaningful_coverage_percent,by_surface_class,by_protocol},meaningful_untested,untested,tested}; summary=true omits item arrays"},
                {"method": "GET", "path": "/api/agent/preflight?host=<optional-target-host>&url=<optional-exact-url>", "auth": True,
                 "description": "Start-of-session readiness check. Verifies authoritative Burp scope inventory/exact URL status, the local Proxy and PortSwigger MCP listeners, knowledge, queue, fixtures, confirmations, and optional auth/latest.",
                 "returns": "{status: ok|warn, checks: {burp_scope,burp_proxy_listener,portswigger_mcp,workspace_files,project_profile,queue,fixtures,confirmations,auth_latest?}, warnings,next_steps}"},
                {"method": "GET", "path": "/api/agent/browseros/readiness?url=<optional-exact-scoped-url>", "auth": True,
                 "description": "Truthful BrowserOS readiness. Separately probes process/CDP health, MCP initialize, tools/list, and whether the supplied exact target URL is visible in Burp Proxy history. This endpoint sends no target traffic.",
                 "returns": "{status: ready|degraded|unavailable, process_alive, cdp, mcp: {initialize,tools_list,ready,failure_stage}, proxy_verification: {required,observed,history_indices}, recovery_actions}"},
                {"method": "GET", "path": "/api/agent/scope?url=<optional-exact-url>&limit=500&summary=true", "auth": True,
                 "description": "Get Burp Suite's authoritative scope. Without url, returns observed in-scope services and URL examples from Burp's site map. With url, returns the exact callbacks.isInScope decision used by all request guards.",
                 "returns": "{source: burp_suite, authoritative: true, services, observed_urls} or {url, scope_guard}"},
                {"method": "GET", "path": "/api/agent/project-profile?include_stale=false", "auth": True,
                 "description": "Get project context: allowed state-changing actions, host auth models, test roles, and notes. Legacy in_scope_hosts/in_scope_paths fields are informational only; Burp Suite is always authoritative for scope.",
                 "returns": "{project_profile: {in_scope_hosts, in_scope_paths, allowed_state_changes, auth_schemes, roles, notes, updated_at}, guidance}"},
                {"method": "POST", "path": "/api/agent/project-profile", "auth": True,
                 "description": "Merge structured project context for authorization models, roles, auth schemes, and allowed state changes. Legacy scope fields may be stored as notes but never authorize traffic.",
                 "body": {"allowed_state_changes": [{"method": "POST", "path_contains": "/profile", "description": "profile edits are allowed"}], "auth_schemes": {"api.example.com": {"headers": ["X-Member-Token"], "cookies": []}}, "roles": ["customer", "admin"], "notes": "optional"}},
                {"method": "POST", "path": "/api/agent/project-profile/import-notes", "auth": True,
                 "description": "Parse free-form kickoff notes into project profile metadata. Burp Suite scope remains authoritative regardless of imported host/path notes.",
                 "body": {"notes": "free-form notes text", "source": "optional label"}},
                {"method": "GET", "path": "/api/agent/knowledge?category=<optional>&status=<optional>&tag=<optional>&limit=200&include_stale=false", "auth": True,
                 "description": "Persistent assessment knowledge base: target observations, endpoint notes, risk leads, assumptions, tested controls, object-model notes, blockers, and chain ideas. Read this before automated testing, variant analysis, and session resume.",
                 "returns": "{knowledge: {entries, sources, updated_at}, entries: [{id, category, title, detail, tags, status, confidence, source, host, path, next_step}], count, total, guidance}"},
                {"method": "POST", "path": "/api/agent/knowledge", "auth": True,
                 "description": "Create or update durable target knowledge. Use notes for pasted observations or entries for structured leads. Raw secret-looking values are redacted.",
                 "body": {"notes": "optional free-form notes", "entry": {"category": "lead|assumption|tested_control|endpoint|auth|business_rule|object_model|risk|blocker|chain_idea|note", "title": "short label", "detail": "what was learned", "tags": ["authorization"], "status": "open|tested|confirmed|not_vulnerable|blocked", "confidence": "observed|inferred|user_provided", "host": "optional", "path": "optional", "next_step": "optional"}, "entries": ["optional list of entry objects"], "source": "optional label", "full_response": "optional boolean; default false"},
                 "returns": "{status: updated, created, updated, entry_ids, total}; use full_response=true to return entries and knowledge"},
                {"method": "GET", "path": "/api/agent/attack-surface?host=<optional>&status=<optional>&limit=500", "auth": True,
                 "description": "Persistent application-wide discovery inventory. Tracks scoped routes plus parameters, roles, states, workflows, protocols, discovery sources, browser visits, response visibility, relevant techniques, and test status independently of Agent A findings.",
                 "returns": "{attack_surface:{entries,updated_at},count,total,snapshot,guidance}"},
                {"method": "POST", "path": "/api/agent/attack-surface", "auth": True,
                 "description": "Upsert application-surface observations from visible BrowserOS, Burp history/site map, JavaScript/API specification extraction, or active testing. Each exact URL is checked against authoritative Burp scope before storage.",
                 "body": {"entry": {"url": "required absolute in-scope URL", "method": "GET", "parameters": [{"name": "id", "type": "query|body|path|header|cookie"}], "roles": ["member"], "states": ["authenticated"], "workflows": ["checkout"], "protocols": ["https"], "sources": ["browseros"], "browser_visited": True, "response_seen": True, "techniques": ["authorization"], "techniques_tested": [], "techniques_blocked": [], "technique_results": [{"technique": "authorization", "outcome": "confirmed|not_vulnerable|gated", "baseline_status": 200, "test_status": 403, "control_status": 200, "evidence": "semantic comparison", "control_proof": "expected allow/deny invariant", "finding_id": "required when confirmed", "positive_signal": False}], "status": "observed|unexplored|planned|testing|tested|blocked", "risk": "unknown|low|medium|high|critical"}, "entries": "optional list"},
                 "returns": "{status,accepted,rejected,snapshot,guidance}"},
                {"method": "GET", "path": "/api/agent/attack-surface/review?queue_id=<optional>", "auth": True,
                 "description": "Read-only deterministic discovery-overwatch review. For Full App Assessment, combines the inventory with campaign surface snapshots and returns route/browser/high-risk/role/saturation blockers.",
                 "returns": "{ready_to_complete,current,requirements,stable_passes,snapshot_count,deltas,blockers,queue_id}"},
                {"method": "POST", "path": "/api/agent/attack-surface/review", "auth": True,
                 "description": "Persist the deterministic overwatch review on a Full App Assessment queue item. Completion remains blocked until a recorded review is currently ready.",
                 "body": {"queue_id": "required Full App Assessment queue id"},
                 "returns": "{ready_to_complete,current,requirements,stable_passes,blockers,reviewed_at}"},
                {"method": "GET", "path": "/api/findings?limit=100&offset=0&fields=id,title,severity", "auth": True,
                 "returns": "{findings:[{id,stable_id,legacy_numeric_id,version,...}],total,next_offset,has_more,stable_order}"},
                {"method": "GET", "path": "/api/findings/<id>?summary=true|include_raw=true|fields=id,title,response_data", "auth": True,
                 "description": "Get one finding. Default omits raw request_data/response_data and returns previews/lengths to avoid huge static JS bodies; include_raw=true or fields=... returns specific raw fields.",
                 "returns": "{id, title, detail, evidence, request_data_preview, response_data_preview, request_data_length, response_data_length, raw_omitted, ...}"},
                {"method": "POST", "path": "/api/findings", "auth": True,
                 "description": "Idempotently create a finding. Supply deduplication_key; agent_status=valid requires the exact PoC request and automatically creates one deduplicated Burp Repeater tab named Finding <daf_id>.",
                 "body": {"url": "required", "title": "required", "severity": "Critical|High|Medium|Low|Information", "confidence": "Certain|Firm|Tentative",
                          "detail": "optional", "cwe": "optional", "evidence": "optional", "remediation": "optional", "owasp": "optional",
                          "ai_confidence": "optional int 0-100", "request_data": "required when agent_status=valid; exact confirmed PoC request", "response_data": "optional",
                          "agent_status": "optional (default: valid)", "agent_priority": "optional (default: P2)", "agent_rationale": "optional",
                          "collaborator_evidence": "required for valid SSRF: a registered Burp Collaborator payload plus either a confirmed interaction or structured ssrf_inband_evidence when egress is unavailable",
                          "ssrf_inband_evidence": "optional fallback with request,response,target,proof_marker,control_proof,test_status,control_status; still requires a registered Collaborator attempt",
                          "deduplication_key": "recommended caller-stable key", "active_test_recipe": "optional object with hypothesis, active_test_type, mutation_hint, expected signals, max_requests, needs_second_user, safety_notes"},
                 "returns": "{status,disposition,created,matched,id,stable_id,legacy_numeric_id,version,match_reason,poc_repeater}"},
                {"method": "GET", "path": "/api/findings/<id>", "auth": True,
                 "returns": "finding object with full detail, evidence, cwe, owasp, remediation, notes"},
                {"method": "POST", "path": "/api/findings/<immutable-id>/triage", "auth": True,
                 "description": "Update one finding. Recipe updates require the immutable ID and expected_version; conflicts return 409. Deletions preserve every surviving ID.",
                "body": {"expected_version": "required for active_test_recipe updates", "status": "valid|false_positive|duplicate|already_covered|needs_investigation|untouched",
                          "severity": "optional Critical|High|Medium|Low|Information",
                          "priority": "P1|P2|P3|P4|defer",
                          "rationale": "short reason",
                          "active_test_recipe": "optional updated active-agent handoff object",
                          "duplicate_of": "required for duplicate unless duplicate_evidence_match is supplied",
                          "duplicate_evidence_match": "required for duplicate unless duplicate_of is supplied",
                          "set_fp": "optional bool - also set the existing false-positive flag"}},
                {"method": "POST", "path": "/api/findings/triage", "auth": True,
                 "description": "Bulk update agent triage verdicts and optional severity overrides for multiple findings. status=duplicate or status=already_covered deletes those findings automatically. duplicate requires rationale plus duplicate_of or duplicate_evidence_match.",
                 "body": {"updates": [{"id": 2, "status": "duplicate", "severity": "Low", "priority": "defer", "rationale": "same endpoint, parameter, root cause, and evidence as finding 1", "duplicate_of": 1}]}},
                {"method": "POST", "path": "/api/findings/<immutable-id>/poc-repeater", "auth": True,
                 "description": "Create or repair the single required editable PoC Repeater tab for a finding. Identical requests are deduplicated by SHA-256. This creates a tab but does not execute the request.",
                 "body": {"request": "exact confirmed raw HTTP request; optional when finding.request_data is already populated", "queue_id": "optional", "force": "optional false; true intentionally creates a replacement tab"},
                 "returns": "{status:ok,poc_repeater:{created,tab_name,request_sha256,url,queue_id,deduplicated}}"},
                {"method": "GET", "path": "/api/agent/queue", "auth": True,
                 "description": "Index only: detail_required=true and critical completion/safety constraints are included; always read detail_endpoint before execution.",
                 "returns": "{queue:[{id,status,detail_required,detail_endpoint,request_budget,completion_constraints,fixture_blocked,state_change_policy,next_action}],count}"},
                {"method": "POST", "path": "/api/agent/queue/finding", "auth": True,
                 "description": "Queue exactly one existing finding for Agent B validation using its immutable id. Rejects an active duplicate queue item.",
                 "body": {"finding_id": "required immutable id/stable_id", "context": "optional operator guidance", "browser_verify": "optional bool"},
                 "returns": "{status:queued,id,source:findings,finding_id}"},
                {"method": "POST", "path": "/api/agent/queue/automated-testing", "auth": True,
                 "description": "Queue automated active testing focused on the current findings list. The agent should verify every visible Agent A finding not yet tested by Agent B, update each finding or mark it Gated, and may use one umbrella linked_validation goal if every linked finding is accounted for. /api/agent/queue/risk-hunt remains as a compatibility alias.",
                 "body": {"context": "optional user guidance", "focus": "optional risk area or host/path to emphasize", "browser_verify": "optional bool"},
                 "returns": "{status: queued, id, source: risk_hunt, message}"},
                {"method": "POST", "path": "/api/agent/queue/full-app-assessment", "auth": True,
                 "description": "Queue application-wide visible discovery plus active testing beyond Agent A's supplied requests. BrowserOS is forced through Burp; the campaign persists an attack-surface map, requires repeated surface diffs, one bounded read-only LLM coverage overwatch, and deterministic completion review.",
                 "body": {"context": "optional user guidance", "focus": "optional app area", "seed_url": "optional in-scope seed", "request_budget": "optional 1-200, default 120", "minimum_routes": "optional default 20", "minimum_browser_routes": "optional default 10", "required_stable_passes": "optional default 2", "expected_roles": ["optional role names"]},
                 "returns": "{status: queued, id, source: risk_hunt, mode: campaign_full_app_assessment, campaign_type: full_app_assessment, browser_verify: true}"},
                {"method": "POST", "path": "/api/agent/attack-surface/overwatch", "auth": True,
                 "description": "Run one read-only configured-LLM review per changed Full App checkpoint over the compact route/parameter/technique matrix. Identical checkpoints return the cached review. It challenges missing vulnerability classes, 5xx-as-safe conclusions, positive execution signals, bad durable assumptions, and under-classified findings; it never sends target traffic.",
                 "body": {"queue_id": "required active Full App Assessment id"},
                 "returns": "{reviewed_at,duration_ms,provider,model,route_count,finding_count,read_only:true,report:{ready_to_complete,missing_tests,challenged_conclusions,underclassified_findings,summary}}"},
                {"method": "POST", "path": "/api/agent/queue/try-harder", "auth": True,
                 "description": "Queue a stronger autonomous web app pentest pass. Agent B must first expand discovery through advertised native Burp crawl/audit plus visible BrowserOS browsing through Burp, meet the measured dynamic endpoint coverage contract, and try to find one previously undiscovered High or Critical vulnerability. Stop immediately after that finding is confirmed and written, or finish under the bounded negative-result contract only after coverage is sufficient or exact discovery blockers are Gated. Findings created from this queue are stored with a (TH) title prefix.",
                 "body": {"context": "optional user guidance", "focus": "optional risk area or host/path to emphasize", "browser_verify": "optional bool", "minimum_coverage_percent": "optional 20-90, default 50; final floor is normally at least 20 points above baseline, capped at 80"},
                 "returns": "{status: queued, id, source: risk_hunt, mode: try_harder, message}"},
                {"method": "POST", "path": "/api/agent/campaign/crawl-audit", "auth": True,
                 "description": "Queue Agent B to use Burp MCP native crawl/audit capabilities for scoped discovery, then re-run endpoint and parameter coverage. This fills the discovery gap that passive site-map-only coverage can miss.",
                 "body": {"context": "optional user guidance", "focus": "optional host/path/app area", "browser_verify": "optional bool"},
                 "returns": "{status: queued, id, source: risk_hunt, mode: campaign_crawl_audit, campaign_type: crawl_audit}"},
                {"method": "POST", "path": "/api/agent/campaign/full-app-assessment", "auth": True,
                 "description": "Alias for /api/agent/queue/full-app-assessment using the shared campaign contract.",
                 "body": {"context": "optional", "focus": "optional", "seed_url": "optional", "request_budget": "optional", "minimum_routes": "optional", "minimum_browser_routes": "optional", "required_stable_passes": "optional"},
                 "returns": "{status: queued, id, source: risk_hunt, mode: campaign_full_app_assessment, campaign_type: full_app_assessment}"},
                {"method": "POST", "path": "/api/agent/campaign/authz-matrix", "auth": True,
                 "description": "Queue Agent B to build and test an authorization matrix across available account/session/object/tenant fixtures. Requires fixtures; otherwise Agent B must return a Gated missing-fixture result.",
                 "body": {"context": "optional user guidance", "focus": "optional flow/object family", "browser_verify": "optional bool"},
                 "returns": "{status: queued, id, source: risk_hunt, mode: campaign_authz_matrix, campaign_type: authz_matrix}"},
                {"method": "POST", "path": "/api/agent/campaign/race", "auth": True,
                 "description": "Queue Agent B to perform a bounded race/concurrency test using Burp MCP/Turbo Intruder or an equivalent parallel runner. Requires explicit safe target and must respect safety gates before state-changing traffic.",
                 "body": {"context": "optional user guidance", "focus": "optional endpoint/flow", "concurrency": "optional small integer", "repeats": "optional small integer", "browser_verify": "optional bool"},
                 "returns": "{status: queued, id, source: risk_hunt, mode: campaign_race, campaign_type: race}"},
                {"method": "POST", "path": "/api/agent/campaign/browser-dom", "auth": True,
                 "description": "Queue Agent B to use BrowserOS through Burp for DOM XSS, postMessage, client-side authz, service worker/cache, console, dialog, and screenshot evidence. browser_verify is forced true.",
                 "body": {"context": "optional user guidance", "focus": "optional page/flow"},
                 "returns": "{status: queued, id, source: risk_hunt, mode: campaign_browser_dom, campaign_type: browser_dom}"},
                {"method": "POST", "path": "/api/agent/campaign/parser-protocol", "auth": True,
                 "description": "Queue Agent B to test specialized surfaces that generic web checks miss: GraphQL, WebSocket, multipart upload/parser behavior, JWT/OAuth/SAML, XML/XXE, and HTTP/2-sensitive behavior. Use Burp MCP and /api/agent/request/http2 where protocol fidelity matters.",
                 "body": {"context": "optional user guidance", "focus": "optional protocol/surface"},
                 "returns": "{status: queued, id, source: risk_hunt, mode: campaign_parser_protocol, campaign_type: parser_protocol}"},
                {"method": "GET", "path": "/api/agent/fixtures?kind=<optional>&include_stale=false", "auth": True,
                 "description": "List structured test context: named accounts, session profiles, object IDs, tenant pairs, and flow states. This is metadata only; keep raw passwords/tokens out of the context store.",
                 "returns": "{fixtures: [{id, kind, label, role, tenant, account_number, object_ids, session_state, session_source, consent_scope, notes, updated_at}], count, guidance}"},
                {"method": "POST", "path": "/api/agent/fixtures", "auth": True,
                 "description": "Create or update one structured fixture. Use this when the user provides test account/object/session context. Do not store raw credentials; store secret_ref or session_source instead.",
                 "body": {"kind": "account|session|object|tenant|flow_state", "label": "required stable name", "role": "optional", "tenant": "optional", "account_number": "optional", "object_ids": "optional object/list", "session_state": "pre_mfa|post_mfa|expired|revoked|fresh", "session_source": "Burp history/browser profile label", "consent_scope": "authorized test scope label", "secret_ref": "optional pointer, not a secret value", "notes": "optional"},
                 "returns": "{status: created|updated, fixture: {...}}"},
                {"method": "POST", "path": "/api/agent/fixtures/import-notes", "auth": True,
                 "description": "Parse free-form kickoff notes into structured test context. Use this for normal assessment notes containing creds, roles, tenants, account numbers, MFA/session hints, and object IDs. Raw secret-looking fields are redacted.",
                 "body": {"notes": "free-form notes text", "source": "optional label such as kickoff_notes or ui_context"},
                 "returns": "{status: imported, created, updated, fixtures, ignored_lines, warnings}"},
                {"method": "GET", "path": "/api/agent/confirmations?kind=<optional>&since_seconds=<optional>", "auth": True,
                 "description": "List human-provided OOB receipt evidence such as OTP, SMS, email, push, or phone-call receipt confirmation.",
                 "returns": "{confirmations: [{id, kind, account_label, destination, received_at, observed_at, source, notes}], count, guidance}"},
                {"method": "POST", "path": "/api/agent/confirmations", "auth": True,
                 "description": "Record user-confirmed OOB evidence. Use this for OTP/SMS/email delivery tests instead of leaving the finding inconclusive.",
                 "body": {"kind": "otp|sms|email|push|phone|other", "account_label": "which test account", "destination": "redacted destination", "received_at": "timestamp user observed", "source": "user|mailbox|sms|browser", "notes": "what was received, redacted"},
                 "returns": "{status: created, confirmation: {...}}"},
                {"method": "GET", "path": "/api/agent/collaborator", "auth": True,
                 "returns": "{payload: 'Burp Collaborator payload string', location: 'collaborator server location'}"},
                {"method": "GET", "path": "/api/agent/collaborator/interactions?payload=<payload>&limit=100", "auth": True,
                 "description": "Poll Burp Collaborator for OOB interactions after injecting a generated payload. Use this to prove blind SSRF, XXE, injection callbacks, webhook calls, and other out-of-band behavior.",
                 "returns": "{payload, count, interactions: [{type, client_ip, time_stamp, interaction_id, request, response, raw_query, ...}], guidance}"},
                {"method": "GET", "path": "/api/agent/auth/latest?host=<host>&limit=50&path_contains=<optional>&include_related=true&verbose=false", "auth": True,
                 "description": "Search recent Burp Proxy history for auth material. Defaults to recommended_auth plus one latest usable credential record per host; verbose=true returns the full matching history. Empty Bearer placeholders are ignored.",
                 "returns": "{host, include_related, related_suffix, searched, recommended_auth: {usable, raw_header_lines, cookie_header, headers, cookies, source_history_indices, source_hosts}, credentials: [{history_index, url, method, host, host_match, request_auth, response_auth}]}"},
                {"method": "GET", "path": "/api/agent/history/http/regex?regex=<pattern>&count=50&cursor=0&include=request,response", "auth": True,
                 "description": "Metadata-only Proxy search by default. Opt into redacted content with include=request,response,headers,previews or equivalent boolean parameters.",
                 "returns": "{cursor,next_cursor,total_matches,has_more,stable_order,metadata_only,items:[{history_index,method,url,status_code,...}]}"},
                {"method": "GET", "path": "/api/agent/queue/<id>", "auth": True,
                 "returns": "full queue item with findings[] array including numeric id and stable_id, active_test_recipe objects, campaign_state for campaign work, flow_requests[] for flow analysis, next_action, and target_curl preview when curl_proxy is recommended"},
                {"method": "GET", "path": "/api/agent/queue/<id>/curl?refresh_auth=true&step=<optional>", "auth": True,
                 "description": "Generate ready-to-run target curl command(s) for curl-capable queue items. Commands always include -x http://127.0.0.1:8080 and X-Eternals-Agent-Note. With refresh_auth=true, auth/latest is applied automatically and stale captured auth headers are replaced. Automated Testing source=risk_hunt has no replayable curl and returns guidance to hand-build scoped proxied requests. HTTP/2-only or pseudo-header-sensitive items return protocol_sensitive_item_requires_portswigger_mcp instead of downgrade-prone curl.",
                 "returns": "{queue_id, refresh_auth, proxy_required, commands: [{command, method, url, auth, scope_guard, safety_gate, requires_confirmation, warnings}], usage}"},
                {"method": "POST", "path": "/api/agent/queue/<id>/repeater", "auth": True,
                 "description": "Create Burp Repeater tabs for a queue item. Structured active_test_recipe.mutations operations are applied to request bytes before each tab is created; mutation_hint remains manual guidance. Prefer a native PortSwigger/Burp MCP Repeater tool when callable.",
                 "body": {"refresh_auth": "optional bool default true"},
                 "returns": "{status: ok, queue_id, created_tabs: [{label,url,mutation,mutation_applied,changes}], warnings, mcp_preference}"},
                {"method": "POST", "path": "/api/agent/queue/<id>/campaign/step", "auth": True,
                 "description": "Update one resumable campaign step. All required steps must be completed, blocked, or skipped before the campaign result is accepted.",
                 "body": {"step_id": "numeric id or key", "status": "pending|running|completed|blocked|failed|skipped", "requests_used": "integer", "artifacts": "list", "note": "optional"},
                 "returns": "{status: updated, queue_id, campaign_step}"},
                {"method": "POST", "path": "/api/agent/scanner/active", "auth": True,
                 "description": "Delegate a high-signal commodity check to Burp's native active scanner. Use for XSS, SQLi, SSTI, open redirect, and similar insertion-point checks after scope/safety gates pass. Burp MCP native scan actions may be used instead when available; this endpoint gives Agent B a stable fallback and job tracker.",
                 "body": {"queue_id": "optional queue item to scan", "finding_id": "optional numeric or stable finding id", "request": "optional raw HTTP request", "url": "optional URL when raw request has no absolute target", "scan_type": "xss|sqli|injection|open_redirect|focused", "insertion_point_offsets": "optional [[start,end], ...] byte offsets", "refresh_auth": "optional bool default true", "confirmed": "required true when safety_gate requires confirmation", "candidate_index": "optional 0-based candidate index for queue items"},
                 "returns": "{status: queued, scanner_job: {id, burp_status, percentage_complete, url, scan_type, scope_guard, safety_gate}, guidance}"},
                {"method": "GET", "path": "/api/agent/scanner/jobs", "auth": True,
                 "description": "List Burp Scanner jobs started through Double Agent, with current Burp queue status and linked scanner findings when available.",
                 "returns": "{jobs: [{id, burp_status, percentage_complete, url, scan_type, scanner_findings}], count}"},
                {"method": "GET", "path": "/api/agent/scanner/jobs/<id>", "auth": True,
                 "description": "Poll one delegated Burp Scanner job. Agent B should poll this before manual payloading and then validate any Burp Scanner finding with a focused repro or browser proof.",
                 "returns": "{scanner_job}"},
                {"method": "POST", "path": "/api/agent/scanner/jobs/<id>/cancel", "auth": True,
                 "description": "Cancel a delegated Burp Scanner job when it is out of scope, unsafe, too noisy, or no longer needed.",
                 "returns": "{status: cancelled, scanner_job}"},
                {"method": "POST", "path": "/api/agent/queue/<id>/claim", "auth": True,
                 "body": "none",
                 "returns": "{status: claimed, id, heartbeat_required_within_seconds, heartbeat_url}",
                 "description": "Claims a pending item. Response includes heartbeat timeout. For mode=try_harder, immediately follow next_action.persistent_agent_goal: get_goal then create_goal when no matching active goal exists, before discovery/testing."},
                {"method": "POST", "path": "/api/agent/queue/<id>/heartbeat", "auth": True,
                 "body": "none",
                 "returns": "{status: ok, id, heartbeat_at, timeout_seconds}",
                 "description": "Refresh the activity timestamp on a claimed item. Call every ~5 minutes during long-running tests to prevent auto-release. Required only for tasks that take longer than the claim timeout (default 15 min)."},
                {"method": "POST", "path": "/api/agent/queue/<id>/release", "auth": True,
                 "description": "Release a claimed work item back to pending when the agent cannot finish it.",
                 "body": {"reason": "optional short reason"},
                 "returns": "{status: pending, id}"},
                {"method": "POST", "path": "/api/agent/queue/<id>/result", "auth": True,
                 "description": "Store durable tested outcome and reproducible evidence for a work item, update linked finding status/risk, and clear the completed item from the active queue. Every finding transitioned to valid must first have its exact editable PoC Repeater tab; otherwise the result remains claimed and returns 409. For automated source=risk_hunt items, queue-level outcome never downgrades all linked findings; only finding_updates mutates findings.",
                 "body": {
                     "outcome": "confirmed|not-vulnerable|gated|blocked-by-missing-fixture|needs-more-info|inconclusive|failed",
                     "severity": "optional linked-finding risk override: Critical|High|Medium|Low|Information",
                    "agent_status": "optional linked-finding status override: valid|false_positive|needs_investigation|untouched",
                     "agent_priority": "optional linked-finding priority override: P1|P2|P3|P4|defer",
                     "agent_rationale": "optional linked-finding rationale override",
                     "finding_updates": [{"id": 1, "severity": "High", "agent_status": "valid", "agent_priority": "P2", "rationale": "Agent B actively validated this finding", "poc_request": "exact confirmed raw request when finding.request_data is absent or stale"}],
                     "assessment": "short overall assessment",
                     "test_results": [{"title": "test name", "outcome": "confirmed", "detail": "what was tested", "evidence": "key response evidence"}],
                    "risk_hunt_goals": "required for automated source=risk_hunt: [{id,category,hypothesis,target,status,evidence,finding_ids,blocker,next_step}]. Automated Testing may use one umbrella linked_validation goal if every linked finding is accounted for through finding_updates or Gated blockers. For mode=try_harder, target one previously undiscovered High/Critical finding, include category=new_discovery goals, and stop immediately after it is confirmed and posted or after the bounded negative-result contract is satisfied.",
                     "persistent_goal": "required for new Try Harder items: {created:true,status:'active',objective:'<active goal>',goal_id:'optional'}. Keep the goal active until this result succeeds, then call update_goal(status=complete). If create_goal is genuinely unavailable, send {tool_unavailable:true,reason:'exact explanation'}.",
                     "discovery_blockers": "required when outcome=gated for Full App Assessment: [{code:'exact blocker code from attack-surface review',detail:'at least 20 characters of evidence'}]; every current review blocker must be covered",
                     "collaborator_evidence": "required for a valid SSRF finding: [{finding_id,payload,interaction_id,type,client_ip,time_stamp}]. Prefer a confirmed interaction. If target egress is unavailable, provide the registered payload attempt plus ssrf_inband_evidence proving a sensitive internal-resource response and a concrete control.",
                     "ssrf_inband_evidence": "optional egress-blocked fallback: {request,response,target,proof_marker,control_proof,test_status,control_status}; does not remove the Collaborator-attempt requirement",
                     "evidence": [{"request": "exact HTTP request or curl", "status_code": 200, "response_snippet": "short response proof", "notes": "repro notes"}],
                     "reproduction": "concise reproduction steps",
                     "notes": ["optional notes"]
                 },
                 "returns": "{status: completed|failed, id, outcome, queue_removed, updated_findings, gated_findings, poc_repeater_tabs, linked_finding_ids, agent_generated_finding_ids, scanner_findings_seen_during_work, passive_findings_seen_during_work}"},
                {"method": "POST", "path": "/api/agent/results/<id>/amend", "auth": True,
                 "description": "Amend a completed queue result when later controls or better evidence arrive. Appends amendment history, updates completed result evidence/test_results/assessment, and can update linked findings.",
                 "body": {"assessment": "optional replacement/additional assessment", "test_results": ["optional appended results"], "evidence": ["optional appended evidence"], "notes": ["optional notes"], "outcome": "optional revised outcome", "finding_updates": "optional linked finding updates"},
                 "returns": "{status: amended, id, outcome, updated_findings, amendments}"},
                {"method": "POST", "path": "/api/agent/queue/clear", "auth": True,
                 "description": "Clear terminal queue items after they have been tested. Claimed/in-progress items are preserved.",
                 "body": {"mode": "completed|all - default completed"},
                 "returns": "{status: ok, removed, remaining}"},
                {"method": "POST", "path": "/api/agent/request", "auth": True,
                 "description": "Fallback/convenience path: fire an HTTP request through Burp's HTTP stack and return structured JSON. For normal manual testing, lower token use, and visible Proxy history notes, use native target curl with -x http://127.0.0.1:8080 and X-Eternals-Agent-Note.",
                 "body": {
                     "host": "required string - hostname only e.g. example.com",
                     "port": "int - default 443",
                     "https": "bool - default true",
                     "request": "required string - full raw HTTP request including headers and body",
                     "comment": "optional Burp history comment, e.g. Agent: IDOR check - baseline owner request",
                     "note": "alias for comment",
                     "agent_note_header": "If request includes X-Eternals-Agent-Note, it is stripped and used as the comment"
                 },
                 "returns": "{status_code: int, headers: [string], body: string}"},
                {"method": "POST", "path": "/api/agent/request/http2", "auth": True,
                 "description": "HTTP/2 execution path. Delegates to the PortSwigger MCP extension on PORTSWIGGER_MCP_URL (default http://127.0.0.1:9876/, SSE at root /) using the send_http2_request tool, preserving HTTP/2 pseudo-header semantics.",
                 "body": {
                     "targetHostname": "required hostname, alias host",
                     "targetPort": "int, alias port, default 443",
                     "usesHttps": "bool, alias https, default true",
                     "pseudoHeaders": "object, e.g. {':method':'GET',':path':'/',':scheme':'https',':authority':'example.com'}; if omitted, method/path are used",
                     "headers": "object of ordinary headers",
                     "requestBody": "string body, alias body",
                     "confirmed": "required true when scope_guard or safety_gate requires confirmation"
                 },
                 "returns": "{transport: 'portswigger_mcp', mcp_tool: 'send_http2_request', url, scope_guard, safety_gate, result: <MCP result>}"},
                {"method": "GET", "path": "/api/agent/mcp/capabilities?refresh=false", "auth": True,
                 "description": "Return cached PortSwigger MCP capability state immediately. refresh=true starts a bounded asynchronous tools/list probe.",
                 "returns": "{status,mcp_url,capabilities:{tools,tool_names,last_success_at,last_probe_at,probe_duration_ms,stale,failure_stage,error},refresh}"},
                {"method": "POST", "path": "/api/agent/mcp/call", "auth": True,
                 "description": "Call a discovered PortSwigger MCP tool through the reusable broker. Target-bearing and destructive actions enforce scope, safety, and confirmation gates.",
                 "body": {"tool_name": "required discovered tool", "arguments": "object matching the discovered inputSchema", "confirmed": "required for gated actions"},
                 "returns": "{status,tool_name,classification,scope_guard,safety_gate,result}"},
                {"method": "GET", "path": "/api/agent/burp/capabilities?refresh=false", "auth": True,
                 "description": "Return cached normalized Burp capabilities immediately; refresh=true starts a bounded asynchronous probe. Includes probe timing, last success, staleness, and failure stage.",
                 "returns": "{status,profile,semantic_actions,double_agent_fallbacks,raw_mcp,guidance}"},
                {"method": "GET", "path": "/api/agent/burp/skill?document=<optional-path>", "auth": True,
                 "description": "Return the complete versioned burpsuite-operator skill through the API so Agent B can load it without a Codex/Claude skill installation or project agent folder. With document omitted, returns every skill document plus combined_markdown in load order.",
                 "returns": "{status,name,version,content_sha256,documents,combined_markdown,load_order,usage} or one selected document"},
                {"method": "GET", "path": "/api/agent/burp/workspace?compact=true&history_limit=25&scope_limit=200", "auth": True,
                 "description": "Compact Burp workspace inventory for Agent B: authoritative scope snapshot, recent Proxy history metadata/comments, finding/queue/job counts, and Scanner jobs. Read this before active testing.",
                 "returns": "{status,scope,recent_proxy_history,counts,scanner_jobs,next}"},
                {"method": "POST", "path": "/api/agent/burp/action/dry-run", "auth": True,
                 "description": "Resolve a stable semantic Burp action to the installed MCP tool and evaluate target extraction, Burp scope, safety, confirmation, and note requirements without executing it.",
                 "body": {"action": "semantic action from /api/agent/burp/capabilities", "arguments": "object matching the selected tool schema", "note": "required for active actions", "confirmed": "required for gated actions"},
                 "returns": "{status,receipt,arguments} or a machine-readable gate/fallback"},
                {"method": "POST", "path": "/api/agent/burp/action", "auth": True,
                 "description": "Execute a normalized Burp action. Active actions require an Agent note; every call returns an auditable receipt with tool, target, scope guard, safety gate, and execution status.",
                 "body": {"action": "semantic action from /api/agent/burp/capabilities", "arguments": "object matching the selected tool schema", "note": "Agent: <work item> - <purpose> - <expected result>", "confirmed": "required for gated actions"},
                 "returns": "{status,receipt,result}"},
            ] + scanner_campaign_api_docs(),
            "rules": [
                "Only test URLs in the queued findings or the same host.",
                "At startup, list all findings and triage them before testing. Use compact detail/evidence fields, not title alone. Triage is a passive classification pass over existing finding data; do not send new exploit traffic during triage unless the user explicitly asks.",
                "While active in a session, monitor /api/findings every 5 minutes and triage any new, untouched, or changed findings before continuing active testing. Post updates through /api/findings/triage so Burp stays current.",
                "Triage status meanings: valid=likely reportable and worth validating, including real low-risk issues when priority=P4; needs_investigation=plausible but evidence is incomplete; false_positive=not a real security issue, zero-risk/non-actionable scanner noise, or contradicted by evidence; duplicate=same endpoint/parameter/root cause/evidence as another finding and will be deleted automatically; already_covered=same endpoint and technique was already tested or covered by a completed queue result and will be deleted automatically; untouched=not reviewed yet.",
                "Agent Status display includes validation source: (A)=Agent A passive finding/triage only, (B triage)=Agent B triaged/classified it but has not actively tested it yet, (B)=Agent B active testing has validated or rejected it through /api/agent/queue/<id>/result or created it via /api/findings.",
                "Use agent_candidate_type to prioritize active work: reportable_candidate first, needs_fixture only after required test context is present, theory_only only when user-requested or cheap, scanner_noise normally skip.",
                "Use /api/agent/scope as the only authoritative scope source. Never request, create, or consult scope.md, and never use project_profile.in_scope_hosts to authorize traffic.",
                "Agent B is a Burp operator, not a generic curl runner. Read /api/agent/burp/capabilities and /api/agent/burp/workspace before active work, select a real semantic action, establish a baseline before mutation, and keep active actions auditable with an Agent note and returned receipt.",
                "POC REPEATER GATE: Before Agent B creates, triages, amends, or updates any finding to status=valid, preserve the exact confirmed request in one editable Burp Repeater tab named Finding <daf_id>. The API creates and deduplicates this tab automatically when request_data/poc_request is present and rejects the valid transition otherwise. Use POST /api/findings/<daf_id>/poc-repeater to repair or explicitly supply it.",
                "At session start, GET /api/agent/burp/skill and follow combined_markdown as the $burpsuite-operator instructions. The API-delivered skill is sufficient; do not block or ask for a local Codex/Claude skill folder.",
                "Prefer POST /api/agent/burp/action over raw /api/agent/mcp/call. The semantic endpoint enforces explicit tool policy, robust target extraction, Burp scope, safety gates, and note hygiene. Use raw MCP calls only for a discovered capability that has no semantic mapping.",
                "Use project_profile.auth_schemes and learned host auth models before treating missing Authorization as missing authentication. Custom headers like X-Member-Token, X-Api-Session, member tokens, and API session tokens are valid auth signals.",
                "Every triage update needs a concrete rationale tied to finding data. Good rationale names the data used: endpoint, parameter, evidence snippet, request/response presence, missing exploitability, or matching duplicate finding.",
                "Mark duplicates with status=duplicate only when root cause, endpoint/parameter, and evidence pattern match; duplicate deletion requires rationale plus duplicate_of or duplicate_evidence_match.",
                "Treat obvious false positives conservatively: explain why they are likely false positives, then deprioritize them unless the user asks for proof.",
                "After triage, update findings through /api/findings/triage so Agent Status, Agent Priority, and Agent Rationale are visible in Burp.",
                "Use active_test_recipe as the active-agent handoff: follow the hypothesis, mutation_hint, expected_vulnerable_signal, expected_safe_signal, max_requests, fixture_requirements, needs_second_user, and safety_notes before inventing a new plan.",
                "For high-signal XSS, SQLi, SSTI, open redirect, or similar insertion-point candidates, prefer Burp Scanner delegation before hand-rolling payload breadth: use a native Burp MCP scan action when available, otherwise POST /api/agent/scanner/active with the queue_id or finding_id. Do not delegate low-signal endpoints blindly. After Burp Scanner returns findings, Agent B must still validate reportable impact with focused evidence before marking a finding valid.",
                "Use campaign endpoints for major coverage gaps that passive AI review and commodity scanner delegation miss: /api/agent/campaign/crawl-audit for Burp MCP crawl/audit discovery, /api/coverage/parameters for parameter-level untested insertion points, /api/agent/campaign/authz-matrix for role/tenant/object authorization matrices, /api/agent/campaign/race for bounded concurrency flaws, /api/agent/campaign/browser-dom for DOM/browser-state bugs, and /api/agent/campaign/parser-protocol for GraphQL/WebSocket/upload/JWT/OAuth/SAML/XML/HTTP2 surfaces.",
                "For source=risk_hunt Automated Testing, verify visible Agent A findings not yet tested by Agent B. One umbrella linked_validation goal is acceptable if every linked finding is accounted for with finding_updates or Gated blockers. Use /api/agent/knowledge, project profile, coverage, report, and Burp history before asking for more context. Use Try Harder when the user wants a deeper solo hunt for new bugs.",
                "Use /api/agent/knowledge as the durable target-environment memory. Store evidence-backed observations, endpoint behavior, business rules, object models, risk leads, assumptions, blockers, tested controls, and chain ideas; read it before asking the user to repeat context.",
                "For IDOR, tenant, MFA, OTP, email, or SMS tests, check /api/agent/fixtures and /api/agent/confirmations first. If next_action.fixture_status.blocked is true, use outcome=blocked-by-missing-fixture and state the missing fixture instead of guessing.",
                "Before testing a queued item, check its exact URL with /api/agent/scope?url=<encoded-url>, call /api/agent/preflight?host=<target-host>&url=<encoded-url>, then follow next_action. If Burp reports in_scope=false, do not send traffic.",
                "Low severity plus low confidence findings should be deferred unless they are unique, user-requested, or can be confirmed with one or two targeted requests.",
                "Ask the user before destructive actions (password change, account delete, payment, etc).",
                "Before asking the user for fresh auth, call /api/agent/auth/latest for the target host and try recommended_auth.raw_header_lines from Burp history.",
                "Use /api/agent/history/http/regex for compact proxy-history discovery, auth/session recovery, parameter pattern search, and variant analysis before asking the user for more context.",
                "auth/latest searches related sibling hosts by default because live browser sessions are often on an app host while queued requests target an API host. Check recommended_auth.source_hosts.",
                "Live browser sessions are often cookie-based. If recommended_auth has a Cookie header but no Authorization header, retry with the Cookie header before asking the user for tokens.",
                "Never claim that all live sessions are expired just because Authorization Bearer is empty. Empty Bearer placeholders are ignored; check cookies and Set-Cookie material too.",
                "If /api/agent/auth/latest has no usable material but BrowserOS has a live session, refresh the relevant BrowserOS page or navigate once in the same-site app through Burp, then call auth/latest again before asking the user for tokens.",
                "Never guess through multiple login endpoints to acquire auth. Try /api/agent/auth/latest once, optionally retry with one recovered token/cookie set, then ask the user.",
                "MANDATORY CURL RULE: every curl request to a target application must include -x http://127.0.0.1:8080. Local Double Agent API calls to http://127.0.0.1:8777 are exempt. Before running any target curl, check the command and add the proxy flag if missing.",
                "For queue items with next_action.recommended_transport=curl_proxy, call /api/agent/queue/<id>/curl?refresh_auth=true and use the generated command instead of hand-building curl. For recommended_transport=portswigger_mcp_http2, do not call /curl or downgrade to HTTP/1.1. If port 9876 is reachable but discovery timed out, call /api/agent/request/http2 once; it uses a fresh MCP session and one reconnect retry. Block only if that execution attempt fails. For recommended_transport=autonomous_hunt, hand-build only scoped target requests through Burp Proxy with X-Eternals-Agent-Note.",
                "If next_action.scope_guard or command scope_guard says requires_confirmation, stop and ask the user before active testing. Never test hosts marked in_scope=false.",
                "If safety_gate.requires_confirmation is true, ask the user before sending the request. This applies to destructive methods and sensitive paths such as payment, password, delete, upload, transfer, or order flows.",
                "For visible Burp Proxy history notes, send tests through the proxy with header X-Eternals-Agent-Note: Agent: <finding/work item> - <test purpose> - <expected result>. The extension copies it into the Proxy history comment and strips the header before the target sees it.",
                "When using /api/agent/request, always include a short comment/note describing what the request is testing. If the note must be visible in the main Proxy history table, prefer a proxied request with X-Eternals-Agent-Note.",
                "BURP MCP / PORTSWIGGER MCP is required for full operation: server is on port 9876 at http://127.0.0.1:9876/ with SSE at root / unless PORTSWIGGER_MCP_URL overrides it. Use discovered tools for generic Burp-native actions. HTTP/2 execution is the exception: /api/agent/request/http2 directly attempts send_http2_request in a fresh session when discovery is stale or timed out. Do not block solely on tools/list when the listener is reachable.",
                "For blind/OOB test cases, generate a payload with /api/agent/collaborator, inject it safely, then poll /api/agent/collaborator/interactions?payload=<payload> for proof before reporting.",
                "Keep assessment under ~2000 chars; each test_results[*].detail under ~500 chars. Store exact reproducible evidence through /api/agent/queue/<id>/result before reporting in chat.",
                "Valid outcome values: confirmed, not-vulnerable, gated, blocked-by-missing-fixture, needs-more-info, inconclusive, failed. Gated is first-class and requires exact blocker evidence.",
                "Prioritize: auth bypass > IDOR > business logic > injection > info disclosure."
            ],
            "example_result_body": {
                "outcome": "confirmed",
                "assessment": "Validated IDOR on /api/users/<id>; CSRF protection is working correctly on state-changing endpoints.",
                "test_results": [
                    {"title": "IDOR on GET /api/users/{id}", "outcome": "confirmed",
                     "detail": "Replaced own id 123 with 124; got foreign user profile.",
                     "evidence": "HTTP 200 with email 'alice@example.com'"}
                ],
                "evidence": [
	                    {"request": "GET /api/users/124 HTTP/1.1\nHost: example.com\nCookie: session=...",
	                     "status_code": 200,
	                     "response_snippet": "{\"email\":\"alice@example.com\"}",
	                     "notes": "Same session could read another user's profile.",
	                     "auth_source": "auth/latest source_history_indices=[42]",
	                     "burp_history_ref": "Proxy history comment: Agent: queue #3 - IDOR probe",
	                     "hypothesis": "Changing the path user id should not return another user's profile."}
                ],
                "reproduction": "Claim queue item, replay own profile request with the path id changed to 124, and observe the 200 response.",
                "notes": ["Session uses HS256 JWT; did not test key confusion."]
            }
        }
        # Authentication was removed when the control API became strictly
        # loopback-only. Normalize legacy per-endpoint metadata here so older
        # schema entries cannot tell a harness to send a bearer header.
        for endpoint in docs.get("endpoints", []):
            endpoint["auth"] = False
        return docs
